---
title: "MH-unique-values"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, warning=FALSE, message=FALSE}

# load libraries
library(dplyr)
library(janitor)
library(readxl)
library(ggplot2)
library(readr)
library(stringr) 
library(lubridate)

```



```{r, warning=FALSE, message=FALSE}
data2012 <- read_excel("MH_nhl_goalies_2012-2013.xls") %>% 
  mutate(`Cap Hit` = as.numeric(`Cap Hit`)) %>%
  mutate(`DOB`= mdy(`DOB`)) %>%
  clean_names() %>% 
  mutate(season = "2012-2013")
data2013 <- read_excel("MH_nhl_goalies_2013-2014.xls") %>% 
  mutate(`Cap Hit` = as.numeric(`Cap Hit`)) %>%
  mutate(`DOB`= mdy(`DOB`)) %>%
  clean_names() %>% 
  rename(`gp` = gp_16,gs = gs_17, sa = sa_21, sv_percent = sv_percent_24) %>% 
  mutate(season = "2013-2012")
data2014 <- read_excel("MH_nhl_goalies_2014-2015.xls") %>% 
  mutate(`Cap Hit` = as.numeric(`Cap Hit`)) %>% 
  mutate(`CHIP` = as.numeric(`CHIP`)) %>%
  mutate(`DOB`= mdy(`DOB`)) %>%
  clean_names() %>%
  rename(gp = gp_17)  %>% 
  mutate(season = "2014-2015")
data2015 <- read_excel("MH_nhl_goalies_2015-2016.xls") %>% 
  mutate(`Cap Hit` = as.numeric(`Cap Hit`)) %>%
  mutate(`CHIP` = as.numeric(`CHIP`)) %>%
  mutate(`DOB`= ymd(`DOB`)) %>%
  clean_names()  %>% 
  mutate(season = "2015-2016")
data2016 <- read_excel("MH_nhl_goalies_2016-2017.xls") %>% 
  mutate(`Cap Hit` = as.numeric(`Cap Hit`))%>%
  mutate(`CHIP` = as.numeric(`CHIP`)) %>%
  mutate(`DOB`= ymd(`DOB`)) %>%
  clean_names()  %>% 
  mutate(season = "2016-2017")
data2017 <- read_excel("MH_nhl_goalies_2017-2018.xls", range = cell_cols("A:DP")) %>% 
  mutate(`Cap Hit` = as.numeric(`Cap Hit`)) %>%
  mutate(`CHIP` = as.numeric(`CHIP`)) %>%
  mutate(`DOB`= ymd(`DOB`)) %>%
  clean_names()  %>% 
  mutate(season = "2017-2018")

help("read_excel")

new <- bind_rows(data2012,data2013,data2014,data2015,data2016,data2017)
new <- new %>% clean_names()


getblanks <-function(blanks){
  blank <- sum(is.na(new[blanks]))
  column_name <- colnames(new[blanks])
  ans <- tibble(column_id = blanks, column_name = column_name,  NA_amount = blank)
  return (ans)
}

response <- tibble()
for (i in 1:ncol(new)) {
  getblanks(i)
  response  <- bind_rows(response,getblanks(i))
}

clean_data <- new


for (y in 1:nrow(response)) {
  if (response[y,"NA_amount"] > 81){
    name_column <-paste((response[y,"column_name"]))
    #print(name_column)
    clean_data <- clean_data %>% select(-name_column)
    }
}

```
